Add API Key Settings Section
Lacerte/clima pull request #195
Opened 2021-08-23 18:04 UTC by PrestoSole

2022-01-19 12:16 UTC, PrestoSole commented on packages/clima_ui/lib/screens/loading_screen.dart
> +import 'dart:async';
I guess this file sneaked in when we tried to rebase the PR

2022-02-07 21:04 UTC, mhmdanas requested changes

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/screens/settings_screen.dart
> +            ),
```suggestion
            const SettingsHeader(title: 'API key'),
```

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/screens/settings_screen.dart
> +                  },
Use fat arrow lambda here.

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/screens/settings_screen.dart
> +                  },
Same as above.

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/screens/weather_screen.dart
> +            fullWeatherStateNotifier.loadFullWeather()
```suggestion
            fullWeatherStateNotifier.loadFullWeather(),
```

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/utilities/snack_bars.dart
> +void showSnackBar(
`showFailureSnackBar` should be refactored to use this.

2022-02-07 21:04 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/dialogs/api_key/api_key_reset_dialog.dart
> +    return AlertDialog(
Use fat arrow syntax here.

2022-02-09 14:52 UTC, mhmdanas approved these changes
LGTM, you can merge when the CI goes green.

2022-02-09 14:54 UTC, merged