Create CONTRIBUTING.md
Lacerte/clima pull request #199
Opened 2021-08-25 11:45 UTC by PrestoSole

2021-08-25 11:56 UTC, mhmdanas commented
Just curious; where did you take this from? It doesn't sound like you wrote it yourself.

2021-08-25 12:02 UTC, PrestoSole commented
Seriously dude? Lol

2021-09-01 06:38 UTC, PrestoSole commented
Add `Attribution` header - check

2021-09-01 14:17 UTC, mhmdanas commented
Just one last thing, can you make "Issues" lowercase?

2021-09-01 14:18 UTC, PrestoSole commented
Line?

2021-09-01 14:19 UTC, mhmdanas commented
Just search for "Issue", there is more than a single usage.

2021-09-06 05:38 UTC, PrestoSole commented
Resolved

2021-09-10 15:10 UTC, mhmdanas requested changes

2021-09-10 15:10 UTC, mhmdanas commented on CONTRIBUTING.md
> +Join #lacerte on Libera Chat and post your question there.
I would comment out this section until we create the libera channel.

2021-11-30 11:41 UTC, mhmdanas approved these changes
To be honest, I feel like the text is not suited for such a small project as Clima, so I think I may revise it later, but generally, looks good.

2021-11-30 11:41 UTC, merged