Update LICENSE to MPLv2
Lacerte/clima pull request #201
Opened 2021-08-25 18:38 UTC by PrestoSole

2021-08-26 14:30 UTC, triallax commented
For us to use MPLv2 properly, we have to add headers to each source code file. Please add a header to one source code file so I can review it if necessary and then you can add it to the rest of the files.

2021-08-29 06:47 UTC, PrestoSole commented
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

https://www.mozilla.org/en-US/MPL/headers/

2021-08-29 14:52 UTC, mhmdanas commented
@PrestoSole sounds good to me.

2021-08-31 14:04 UTC, mhmdanas requested changes

2021-08-31 14:04 UTC, mhmdanas commented on LICENSE
> +
We don't need this line (well, not for now, but it can be added when it's needed). Remove it for now.

2021-09-01 14:28 UTC, mhmdanas commented
You also need to change the license tile in the about page.

2021-09-06 05:41 UTC, PrestoSole commented
Resolved!

2021-09-06 05:42 UTC, PrestoSole commented
Don't merge this PR now though. I don't want to cause conflicts for #220

2021-09-10 14:15 UTC, closed without merging