Create PULL_REQUEST_TEMPLATE.md
Lacerte/clima pull request #216
Opened 2021-08-31 13:28 UTC by PrestoSole

2021-09-01 14:15 UTC, mhmdanas commented
Where did you get this template from? Can you credit them?

2021-09-01 14:19 UTC, PrestoSole commented
That's a template, where to put the credit?

2021-09-01 14:22 UTC, mhmdanas commented
That will need thinking, but it's no excuse for not crediting the original authors.

I would put it in an HTML comment at the very beginning of the file:
```html
<!-- Put the attribution here -->
```
You might also credit them in the README, but I think you should do the HTML comment thing regardless of having the crediting in the README.

2021-09-06 05:56 UTC, PrestoSole commented
Resolved!

2021-09-10 15:00 UTC, mhmdanas requested changes

2021-09-10 15:00 UTC, mhmdanas commented on .github/PULL_REQUEST_TEMPLATE.md
> +By submitting a PR to this repository, you agree to the terms within our [Code of Conduct](https://github.com/lacerte/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https:/
The links are incorrect:
```suggestion
By submitting a PR to this repository, you agree to the terms within our [Code of Conduct](https://github.com/lacerte/clima/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/lacerte/clima/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
```

2021-09-10 15:04 UTC, mhmdanas approved these changes

2021-09-10 15:04 UTC, merged