Big UI Overhaul
Lacerte/clima pull request #220
Opened 2021-09-06 05:24 UTC by PrestoSole

2021-10-21 15:02 UTC, triallax requested changes
Here's the first round of reviews (yes, I'm certain there will be more); code looks generally good to me. The thing I'm most confused about is the regular use of `maxLines: 1`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_data/lib/data_sources/full_weather_remote_data_source.dart
> +          'lon': coordinates.long.toString(),
Not exactly a problem with this PR, but I think I'd prefer to make these fixes in another PR.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/assets/cloudy.svg
> +<?xml version="1.0" encoding="utf-8"?>
We may want to consider minifying those SVG files.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/constants.dart
> +TextStyle kSubtitle1TextStyle(BuildContext context) {
For this function and all the ones below, please use arrows to return the text style directly (i.e. `=>`). Also, I would re-consider the IMO rather poor function names (though our handling of text colors and sizes in the app in general is pretty lousy).

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/modal_buttom_sheet.dart
> +}) {
Same as above; use `=>`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/modal_buttom_sheet.dart
> +      return Column(
Same as above.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/modal_buttom_sheet.dart
> +              overflow: TextOverflow.clip,
Why have these two lines?

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +
```suggestion
/// Returns the weather icon that corresponds to the given `iconCode`.
```

The three slashes will make this appear as documentation for the function.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +      return 'assets/night.svg';
Please add an empty line after each `return` statement here.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +    ///TODO: Add smog icon
```suggestion
    // TODO: Add smog icon
```

Reserve triple slashes for documentation.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +    default:
Having this as the default sounds dangerous to me. What's the purpose?

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +    return PopupMenuButton(
Please use `=>`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/main_info_widget.dart
> +  }) : super(key: key);
```suggestion
  const MainInfoWidget({Key? key}) : super(key: key);
```

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/main_info_widget.dart
> +              maxLines: 1,
Why?

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/main_info_widget.dart
> +              city.name.toUpperCase(),
I'm not sure, but I think having the city name in uppercase looks a little weird.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/hourly_forecasts_widget.dart
> +          ),
```suggestion
          padding: EdgeInsets.symmetric(horizontal: 5.w),
```

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/hourly_forecasts_widget.dart
> +  }) : super(key: key);
```suggestion
  const HourlyForecastsWidget({Key? key}) : super(key: key);
```

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/additional_info_widget.dart
> +                value: '${currentWeather.uvIndex}',
```suggestion
                value: currentWeather.uvIndex.toString(),
```

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/additional_info_tile.dart
> +    return Expanded(
Use `=>`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/additional_info_tile.dart
> +  }) : super(key: key);
```suggestion
  const AdditionalInfoTile({this.title, this.value, Key? key}) : super(key: key);
```

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/settings/settings_tile.dart
> +    return ListTile(
Use `=>`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/settings/settings_header.dart
> +    return Padding(
Use `=>`.

2021-10-21 15:02 UTC, triallax commented on packages/clima_ui/lib/widgets/settings/settings_divider.dart
> +  }) : super(key: key);
```suggestion
  const SettingsDivider({Key? key}) : super(key: key);
```

2021-10-21 15:08 UTC, triallax commented
Also, please mention the issues that this PR fixes in the body, like this: "fixes #1, fixes #2"

2021-10-22 12:43 UTC, prestosole commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +    default:
The `switch case` statement requires that we specify a default value. Among all weather symbols, the day (sun) or cloud icons are the most popular. I'm using the sun icon for now because there is nothing called a 'default' weather icon, at least not in the case of our API Provider; it always gives us an icon code.

2021-10-22 12:49 UTC, prestosole commented on packages/clima_ui/lib/widgets/weather/main_info_widget.dart
> +              city.name.toUpperCase(),
The use of uppercase for the city name is a crucial feature of this design. At least in this design, having it shown without the uppercase looks strange and unappealing.

2021-10-22 12:52 UTC, prestosole commented on packages/clima_ui/lib/utilities/constants.dart
> +TextStyle kSubtitle1TextStyle(BuildContext context) {
I disagree with your claim that the app's handling of font sizes are "lousy." I agree that the function names are terrible, though. Do you have any suggestions for the names?

2021-10-23 12:40 UTC, triallax commented on packages/clima_ui/lib/utilities/weather_icon.dart
> +    default:
Then throw an error in the `default` clause.

2021-11-06 09:00 UTC, mhmdanas requested changes

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/screens/loading_screen.dart
> +                  builder: (BuildContext context) => const WeatherScreen(),
```suggestion
                  builder: (context) => const WeatherScreen(),
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/screens/weather_screen.dart
>            ),
```suggestion
          const FloatingSearchBarAction(child: OverflowMenuButton()),
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +        itemBuilder: (BuildContext context) => <PopupMenuEntry<Menu>>[
```suggestion
        itemBuilder: (context) => [
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +          PopupMenuItem<Menu>(
```suggestion
          PopupMenuItem(
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +          PopupMenuItem<Menu>(
```suggestion
          PopupMenuItem(
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/settings/settings_divider.dart
> +  Widget build(BuildContext context) {
Use fat arrow syntax here.

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/settings/settings_header.dart
> +  const SettingsHeader({required this.title});
```suggestion
  const SettingsHeader({required this.title});

```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/additional_info_widget.dart
> +  }) : super(key: key);
```suggestion
  const AdditionalInfoWidget({Key? key}) : super(key: key);
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/additional_info_widget.dart
> +    );
```suggestion
    );

```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/daily_forecasts_widget.dart
> +  }) : super(key: key);
```suggestion
  const DailyForecastsWidget({Key? key}) : super(key: key);
```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/hourly_forecasts_widget.dart
> +    );
```suggestion
    );

```

2021-11-06 09:00 UTC, triallax commented on packages/clima_ui/lib/widgets/weather/main_info_widget.dart
> +    );
```suggestion
    );

```

2021-11-06 11:55 UTC, PrestoSole commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +          PopupMenuItem<Menu>(
I think we should specify the type here.

2021-11-06 11:55 UTC, PrestoSole commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +          PopupMenuItem<Menu>(
See above.

2021-11-06 11:56 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/others/overflow_menu_button.dart
> +          PopupMenuItem<Menu>(
No, it is not necessary.

2021-11-06 12:24 UTC, mhmdanas approved these changes

2021-11-06 12:25 UTC, merged