Implement forecast into the app.
Lacerte/clima pull request #62
Opened 2021-03-03 12:13 UTC by PrestoSole

2021-03-04 15:47 UTC, mhmdanas commented on packages/clima_data/lib/data_sources/forecast_remote_data_source.dart
> +const String apiKey = '4bef3adf2fcb90307c2bf5feac75a2ba';
This should probably be put in a separate `constants.dart` file in `clima_data` or something.

2021-03-04 15:47 UTC, mhmdanas commented on packages/clima_data/lib/data_sources/forecast_remote_data_source.dart
> +  Future<Either<Failure, ForecastsModel>> getWeather(City city);
This should be renamed to `getForecasts`.

2021-03-04 15:48 UTC, mhmdanas commented on packages/clima_domain/lib/entities/forecasts.dart
> +  // TODO: implement checkRuntimeType
You probably forgot to remove this comment and the one below.

2021-03-04 15:50 UTC, mhmdanas commented on packages/clima_domain/lib/repos/forecasts_repo.dart
> +final weatherRepoProvider =
This should be renamed to `forecastsRepoProvider`. It should also be overriden with `forecastsRepoImplProvider` in `clima_ui/lib/main.dart` (see https://github.com/CentaurusApps/clima/blob/master/packages/clima_ui/lib/main.dart#L20 for an example).

2021-03-04 15:51 UTC, mhmdanas requested changes
Mostly fine; you should add tests too.

2021-03-04 15:51 UTC, mhmdanas commented
There seems to be some extraneous commits. Can you try to rebase?

2021-03-06 18:05 UTC, mhmdanas commented on packages/clima_data/lib/models/forcasts_model.dart
> +    );
```suggestion
    final cityName = json['city']['name'] as String;

    return ForecastsModel(
      cityName: cityName,
      forecasts: list.map((e) => ForecastModel.fromJson(e, cityName: cityName)).toList(),
    );
```

2021-03-06 18:06 UTC, mhmdanas commented on packages/clima_data/lib/models/forecast_model.dart
> +}
```suggestion
  factory ForecastModel.fromJson(Map<String, dynamic> json, {@required String cityName}) => ForecastModel(
      temperature: (json['main']['temp'] as num).toDouble(),
      tempMax: (json['main']['temp_max'] as num).toDouble(),
      tempMin: (json['main']['temp_min'] as num).toDouble(),
      tempFeel: (json['main']['feels_like'] as num).toDouble(),
      // We multiply by 3.6 to convert from m/s to km/h.
      windSpeed: (json['wind']['speed'] as num).toDouble() * 3.6,
      condition: json['weather'][0]['id'] as int,
      cityName: cityName,
      description: json['weather'][0]['description'] as String,
      time: (json['timezone'] as num).toInt(),
      iconCode: json['weather'][0]['icon'] as String,
      sunrise: json['sys']['sunrise'] as int,
      sunset: json['sys']['sunset'] as int,
      humidity: json['main']['humidity'] as int);
}
```

2021-03-09 14:43 UTC, mhmdanas commented on packages/clima_domain/lib/entities/forecasts.dart
> +        forecasts,
You forgot to add `cityName` here.

2021-03-09 14:44 UTC, PrestoSole commented on packages/clima_domain/lib/entities/forecasts.dart
> +        forecasts,
Oopsie!

2021-03-09 14:44 UTC, mhmdanas requested changes

2021-03-09 14:44 UTC, mhmdanas commented on packages/clima_data/lib/repos/forecasts_repo_impl.dart
> +              (weather) => weather != null && weather.cityName == city.name)) {
```suggestion
              (forecasts) => forecasts != null && forecasts.cityName == city.name)) {
```

2021-03-09 14:44 UTC, mhmdanas commented on packages/clima_domain/lib/use_cases/get_forecasts.dart
> +class GetWeather implements UseCase<Forecasts, GetWeatherParams> {
This should be `GetForecasts`.

2021-03-09 14:45 UTC, mhmdanas commented on packages/clima_domain/lib/use_cases/get_forecasts.dart
> +class GetWeatherParams extends Equatable {
And this should be `GetForecastsParams`.

2021-03-09 14:46 UTC, mhmdanas commented on packages/clima_domain/lib/use_cases/get_forecasts.dart
> +final getWeatherProvider =
This should be `getForecastsProvider`.

2021-03-10 08:14 UTC, mhmdanas approved these changes

2021-03-10 08:15 UTC, merged