Make UI responsive
Lacerte/clima pull request #73
Opened 2021-04-03 13:35 UTC by PrestoSole

2021-04-03 13:36 UTC, PrestoSole commented
Those extraneous commits.....

2021-04-11 07:09 UTC, mhmdanas requested changes

2021-04-11 07:09 UTC, triallax commented on packages/clima_ui/lib/widgets/forecast_horizontal_widget.dart
>      return SizedBox(
I don't think `SizedBox` is necessary here if it doesn't take `width` or `height`.

2021-04-11 07:09 UTC, triallax commented on packages/clima_ui/lib/widgets/current_conditions.dart
> +import 'package:flutter/cupertino.dart';
Please remove this import.

2021-04-11 07:09 UTC, triallax commented on packages/clima_ui/lib/widgets/forecast_widget.dart
>      return SizedBox(
Return the list view directly, as `SizedBox` does nothing without `width` and `height` (I think, please check by running the app).

2021-04-11 07:09 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/weather_swipe_pager.dart
> +        margin: const EdgeInsets.all(5.0),
Can't this be `4` instead?

2021-04-11 07:09 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/weather_swipe_pager.dart
> +// height: MediaQuery.of(context).size.height / 2.6,
Please remove these comments.

2021-04-11 07:09 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/weather_widget.dart
> +      }
This `else if` is not necessary, as the function returns `SizedBox.shrink()` anyway (see line below).

2021-04-11 07:09 UTC, mhmdanas commented on packages/clima_ui/lib/widgets/weather_widget.dart
> +        return const Spacer();
Please use explicit ratios instead of these magic numbers. For example, `0.5625` would be `9.0 / 16.0` (ratio of width to height).

2021-04-13 10:16 UTC, mhmdanas approved these changes

2021-04-13 10:16 UTC, merged